### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fabiommendes** [lappis-unb/salicml#1]
# 0.x
* [ ] Refatorar api do salic (salic-api)
* [ ] Minerar/entender o banco
* [ ]  Treinamento de ferramentas NLP em português/SALICquês
* [ ] Extração de features
* [ ] Classicar enquadramento de projetos 
* [ ] Deteção de anomalias/admissibilidade
* [ ] Verificação e validação dos modelos

# 1.0
* [ ] Integrar inteligência às telas de submissão do SALIC
